.GLOBL _spl6
_spl6:

.GLOBL _splx
_splx:

.GLOBL _u
_u:

.GLOBL _fuword
_fuword:

.GLOBL _suword
_suword:

.GLOBL _copyseg
_copyseg:

.GLOBL _fubyte
_fubyte:

.GLOBL _subyte
_subyte:

.GLOBL _clearseg
_clearseg:

.GLOBL _spl1
_spl1:

.GLOBL _spl5
_spl5:

.GLOBL _spl7
_spl7:

.GLOBL _display
_display:

.GLOBL _waitloc
_waitloc:

.GLOBL _addupc
_addupc:

.GLOBL _idle
_idle:

.GLOBL _putchar
_putchar:

.GLOBL _copyout
_copyout:

.GLOBL _save
_save:

.GLOBL _suibyte
_suibyte:

.GLOBL _fuibyte
_fuibyte:

.GLOBL _spl0
_spl0:

.GLOBL _savfp
_savfp:

.GLOBL _resume
_resume:

.GLOBL _fuiword
_fuiword:

.GLOBL _copyiout
_copyiout:

.GLOBL _copyin
_copyin:

.GLOBL _copyiin
_copyiin:

.GLOBL _suiword
_suiword:

.GLOBL _backup
_backup:

.GLOBL _restfp
_restfp:

.GLOBL _stst
_stst:

	ret
